# Generated by Django 6.0 on 2025-12-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervencao',
            options={'verbose_name': 'Intervenção', 'verbose_name_plural': 'Intervenções'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='perfilpaciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
